###

### CF and KNN, Neighborhood Formation

#### Importing the Libraries

In [11]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity as sim

#### Load the Dataset

In [12]:
df = pd.read_csv('/code/github/Kapita-Selekta/01_ks_11_9.ipynb/cf_data_matrix.csv')

df.head()

  user item  rating
0   U1   I1     4.0
1   U2   I1     1.0
2   U3   I1     4.0
3   U4   I1     5.0
4   U5   I1     4.0

#### Rate and Fill the Nan Value

In [13]:
rating_matrix = df.pivot(index='user', columns="item", values="rating").fillna(0)

rating_matrix

item   I1  I10  I11  I12   I2   I3   I4   I5   I6   I7   I8   I9
user
U1    4.0  0.0  0.0  2.0  1.0  0.0  3.0  3.0  4.0  5.0  3.0  5.0
U10   1.0  0.0  5.0  1.0  2.0  0.0  5.0  0.0  1.0  4.0  0.0  5.0
U2    1.0  4.0  3.0  2.0  4.0  5.0  5.0  0.0  1.0  0.0  3.0  4.0
U3    4.0  3.0  3.0  4.0  3.0  5.0  3.0  1.0  3.0  5.0  5.0  3.0
U4    5.0  4.0  1.0  5.0  2.0  2.0  1.0  2.0  4.0  5.0  0.0  4.0
U5    4.0  1.0  0.0  0.0  0.0  4.0  0.0  5.0  1.0  4.0  2.0  1.0
U6    3.0  3.0  5.0  3.0  5.0  0.0  3.0  1.0  4.0  0.0  5.0  0.0
U7    1.0  4.0  5.0  4.0  1.0  3.0  5.0  3.0  2.0  3.0  5.0  1.0
U8    5.0  0.0  4.0  3.0  4.0  0.0  1.0  3.0  2.0  0.0  5.0  1.0
U9    2.0  5.0  5.0  0.0  2.0  5.0  0.0  1.0  2.0  2.0  3.0  0.0

#### Compute

In [14]:
user_sim = sim(rating_matrix)

user_sim

array([[1.        , 0.68118807, 0.50876697, 0.78000239, 0.81618285,
        0.69110895, 0.5463696 , 0.63099803, 0.63678479, 0.37277509],
       [0.68118807, 1.        , 0.65847538, 0.65079365, 0.58686146,
        0.29364007, 0.53571429, 0.64653345, 0.4709505 , 0.41210713],
       [0.50876697, 0.65847538, 1.        , 0.8180134 , 0.59559429,
        0.39476596, 0.72020745, 0.80057095, 0.57158459, 0.72970012],
       [0.78000239, 0.65079365, 0.8180134 , 1.        , 0.83905846,
        0.70272837, 0.76388889, 0.87338729, 0.73258967, 0.7895928 ],
       [0.81618285, 0.58686146, 0.59559429, 0.83905846, 1.        ,
        0.66864063, 0.58901904, 0.66193903, 0.58917612, 0.58658117],
       [0.69110895, 0.29364007, 0.39476596, 0.70272837, 0.66864063,
        1.        , 0.335992  , 0.56493268, 0.52124669, 0.60074212],
       [0.5463696 , 0.53571429, 0.72020745, 0.76388889, 0.58901904,
        0.335992  , 1.        , 0.8039133 , 0.88425863, 0.70359754],
       [0.63099803, 0.64653345, 0.80057095, 0.87338729, 0.66193903,
        0.56493268, 0.8039133 , 1.        , 0.69527472, 0.77093468],
       [0.63678479, 0.4709505 , 0.57158459, 0.73258967, 0.58917612,
        0.52124669, 0.88425863, 0.69527472, 1.        , 0.57987933],
       [0.37277509, 0.41210713, 0.72970012, 0.7895928 , 0.58658117,
        0.60074212, 0.70359754, 0.77093468, 0.57987933, 1.        ]])

In [17]:
df_user_sim = pd.DataFrame(user_sim, index=rating_matrix.index, columns=rating_matrix.index)

df_user_sim

user,U1,U10,U2,U3,U4,U5,U6,U7,U8,U9
user,,,,,,,,,,
U1,1.000000,0.681188,0.508767,0.780002,0.816183,0.691109,0.546370,0.630998,0.636785,0.372775
U10,0.681188,1.000000,0.658475,0.650794,0.586861,0.293640,0.535714,0.646533,0.470951,0.412107
U2,0.508767,0.658475,1.000000,0.818013,0.595594,0.394766,0.720207,0.800571,0.571585,0.729700
U3,0.780002,0.650794,0.818013,1.000000,0.839058,0.702728,0.763889,0.873387,0.732590,0.789593
U4,0.816183,0.586861,0.595594,0.839058,1.000000,0.668641,0.589019,0.661939,0.589176,0.586581
U5,0.691109,0.293640,0.394766,0.702728,0.668641,1.000000,0.335992,0.564933,0.521247,0.600742
U6,0.546370,0.535714,0.720207,0.763889,0.589019,0.335992,1.000000,0.803913,0.884259,0.703598
U7,0.630998,0.646533,0.800571,0.873387,0.661939,0.564933,0.803913,1.000000,0.695275,0.770935
U8,0.636785,0.470951,0.571585,0.732590,0.589176,0.521247,0.884259,0.695275,1.000000,0.579879
U9,0.372775,0.412107,0.729700,0.789593,0.586581,0.600742,0.703598,0.770935,0.579879,1.000000